### ISSUE TITLE
Get Wallet address and balance by keys

### ISSUE THREAD

**Issue by GoNextGroup** [everscale-actions/everscale-dotnet#9]
I'm a newbie in Free TON usage. I'm trying to understand how to get my own wallet address, when I generate my wallet phrase? I have phrase, I can get public and private keys, but not a wallet address/balance.(( Could you explain me this with your cool library? Is it possible? Thank you.

**Comment by ch1seL** [comment]
Hi, @GoNextGroup! I'm sorry to keep you holding.

To get a wallet address and balance you should use your contract files(tvm and abi.json), please see [samples](https://github.com/ton-actions/ton-client-dotnet/blob/38c55ab755faf02fceff2b941f5feea154b08ccc/samples/MessageReceiverService/Worker.cs#L45). 

This library is just a wrapper of [TON-SDK](https://github.com/tonlabs/TON-SDK), feel free to ask questions in telegram chats 
https://t.me/ton_sdk or https://t.me/ton_actions_chat to get quicker answers. 

Thank you!
